### PR TITLE
fix: update pdm-multirun to pdm 2.26 API

### LINKED ISSUE #11: bug: multirun produce error with pdm 2.16
### Description of the bug

After update pdm to version `2.16.1` run pdm generate this error: 
```
ERROR: Failed to load plugin multirun=pdm_multirun.plugin:multirun: cannot import name 'Project'
from 'pdm.cli.commands.run'
```

### To Reproduce

Just add pdm-multirun in tool.pdm.plugins

### Environment information

```bash
- __System__: Linux-6.9.5-100.fc39.x86_64-x86_64-with-glibc2.38
- __Python__: cpython 3.12.3
- __Environment variables__:
  - `PYTHONPATH`: `$HOME/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/pep582`
- __Installed packages__:
  - `pdm-multirun` v0.0.0
```

### PR DESCRIPTION
**Pull request by natir**
Fix #11

### CODE REVIEW

**Review by pawamoy — APPROVED** [review]
LGTM, thanks a lot!

**Comment by pawamoy** [comment]
Quality failure unrelated, test failures due to new features of PDM. I don't want to invest time to fix it since I don't really use PDM or this plugin anymore, but the fix is good anyway so I will merge and release.

**Comment by natir** [comment]
Maybe you could archive this project and add message in Readme

**Comment by pawamoy** [comment]
It's a bit soon to archive it, but I added a warning to the readme :+1:

**Pull request merged**
